name: Publish on NPM
on:
    push:
        branches: [master]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: pnpm/action-setup@v4
              with:
                  version: 9
            - run: pnpm install
            - run: pnpm prettier-check
            - uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
